# Generated by Django 5.2.15 on 2026-06-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('custody', '0004_systemalert_is_escalated_alter_facility_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_officers', to='custody.facility'),
        ),
    ]
