# Generated by Django 5.2.15 on 2026-06-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_facility'),
        ('judiciary', '0002_court_remove_courtcase_court_name_courtcase_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clerks', to='judiciary.court'),
        ),
    ]
