# Generated by Django 5.2.15 on 2026-06-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
