# Generated by Django 5.2.15 on 2026-06-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_alter_facility_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
    ]
