# Generated by Django 5.2.15 on 2026-06-22 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0003_alter_facility_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemalert',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='commander',
            field=models.ForeignKey(limit_choices_to={'role': 'FACILITY_COMMANDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
