# Generated by Django 5.2.15 on 2026-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0005_alter_facility_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemalert',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
