# Generated by Django 5.2.15 on 2026-06-16 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('court_name', models.CharField(max_length=255)),
                ('charge_summary', models.TextField()),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('DISMISSED', 'Dismissed'), ('CONVICTED', 'Convicted')], default='ONGOING', max_length=50)),
                ('next_court_date', models.DateField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='custody.inmate')),
            ],
        ),
        migrations.CreateModel(
            name='HearingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('BAIL_GRANTED', 'Bail Granted'), ('ADJOURNED', 'Adjourned'), ('DISMISSED', 'Dismissed'), ('SENTENCED', 'Sentenced')], max_length=50)),
                ('bail_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bail_conditions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='judiciary.courtcase')),
                ('clerk', models.ForeignKey(limit_choices_to={'role': 'COURT_CLERK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
