# Generated by Django 5.2.15 on 2026-06-25 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judiciary', '0002_court_remove_courtcase_court_name_courtcase_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearinglog',
            name='hearing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
