# Generated by Django 5.2.15 on 2026-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judiciary', '0003_alter_hearinglog_hearing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcase',
            name='next_court_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
